const KEY='clara_v2';
const old=JSON.parse(localStorage.getItem(KEY)||'null');
let s=old||{products:INITIAL_PRODUCTS,batches:[],movements:[],orders:[],kiz:[],settings:{spp:.2578,commission:.435,acq:.04,ads:.05,tax:.06,buyout:.60,logistics:.25,returnLogistics:50,printAgentUrl:'http://127.0.0.1:17890'},selectedOrder:null,analytics:{ads:[],search:[],competitors:[],logistics:[]}};
if(!s.products?.length)s.products=INITIAL_PRODUCTS;if(!s.settings)s.settings={spp:.2578,commission:.435,acq:.04,ads:.05,tax:.06,buyout:.60,logistics:.25,returnLogistics:50,printAgentUrl:'http://127.0.0.1:17890'};if(!s.analytics)s.analytics={ads:[],search:[],competitors:[],logistics:[]};
function save(){localStorage.setItem(KEY,JSON.stringify(s))} function money(x){return Math.round(Number(x)||0).toLocaleString('ru-RU')+' ₽'} function pc(x){return ((Number(x)||0)*100).toFixed(1)+'%'} function p(a){return s.products.find(x=>x.article===a)} function esc(x){return String(x??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;')}
const titles={home:'Главная',products:'Товары',production:'Производство',warehouse:'Склад',wb:'Wildberries',fbs:'FBS — сборка',mark:'Честный ЗНАК',analytics:'Аналитика продаж',unit:'Unit-экономика',reports:'Отчёты',settings:'Настройки'};
function show(page){document.getElementById('title').textContent=titles[page];document.getElementById('crumb').textContent='CLARA / '+titles[page];document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.getAttribute('onclick')?.includes("'"+page+"'")));({home,products,production,warehouse,wb,fbs,mark,analytics,unit,reports,settings}[page])();save()}
function toast(t){const e=document.getElementById('toast');e.textContent=t;e.className='toast';clearTimeout(window._toast);window._toast=setTimeout(()=>e.className='',2300)}
function stockByArticle(){const by={};s.movements.forEach(m=>{by[m.article]=(by[m.article]||0)+(m.type==='sale'||m.type==='toWB'||m.type==='writeoff'?-m.qty:m.qty)});return by} function stockTotal(){return Object.values(stockByArticle()).reduce((a,b)=>a+b,0)}
function home(){let made=s.batches.reduce((a,b)=>a+b.qty,0),sent=s.movements.filter(m=>m.type==='toWB').reduce((a,m)=>a+m.qty,0),sold=s.movements.filter(m=>m.type==='sale').reduce((a,m)=>a+m.qty,0),fbs=s.orders.filter(o=>!['Отгружен','Отменён'].includes(o.status)).length;document.getElementById('app').innerHTML=`<div class=hero><div><h2>CLARA V4</h2><div class=muted>Товар → производство → склад → FBS → КИЗ → WB → аналитика</div></div><div class=seg><button class=btn onclick="show('fbs')">Открыть FBS</button><button class="btn light" onclick="show('analytics')">Аналитика</button></div></div><div class=grid><div class=kpi><small>Артикулов</small><strong>${s.products.length}</strong></div><div class=kpi><small>Произведено</small><strong>${made} шт.</strong></div><div class=kpi><small>Склад CLARA</small><strong>${Math.max(0,stockTotal())} шт.</strong></div><div class=kpi><small>FBS в работе</small><strong>${fbs}</strong></div></div><div class=grid style="margin-top:14px"><div class=kpi><small>Отправлено на WB</small><strong>${sent}</strong></div><div class=kpi><small>Продано</small><strong>${sold}</strong></div><div class=kpi><small>СПП</small><strong>${pc(s.settings.spp)}</strong></div><div class=kpi><small>КВВ</small><strong>${pc(s.settings.commission)}</strong></div></div><div class=grid3 style="margin-top:18px"><div class="card goodbox"><b>Производство</b><p class=note>Количество вводится отдельно по каждому размеру. Кнопка «Добавить на склад» сразу создаёт приход.</p><button class="btn light" onclick="show('production')">Производство</button></div><div class="card goodbox"><b>FBS</b><p class=note>Скан заказа → стикер → КИЗ → проверка → готов к отгрузке.</p><button class="btn light" onclick="show('fbs')">Сборка FBS</button></div><div class="card warnbox"><b>API</b><p class=note>В V3 подготовлены экраны. Реальные WB/ЧЗ данные подключаются через серверный контур без хранения токенов в браузере.</p><button class="btn light" onclick="show('settings')">Настройки API</button></div></div>`}
function products(){let q=(window.prodQ||'').toLowerCase();let rows=s.products.filter(x=>(x.article+' '+x.name+' '+(x.wbArticle||'')+' '+(x.barcode||'')).toLowerCase().includes(q)).map(x=>`<tr><td><b>${esc(x.article)}</b></td><td>${esc(x.name)}</td><td>${esc(x.wbArticle||'—')}</td><td>${esc(x.barcode||'—')}</td><td>${money(x.cost)}</td><td>${money(x.price)}</td><td>${x.discount||0}%</td><td>${(x.gtin||'')?'есть':'—'}</td><td><button class="btn light" onclick="editProduct('${esc(x.article)}')">Открыть</button></td></tr>`).join('');document.getElementById('app').innerHTML=`<div class=hero><div><h2>Товары</h2><div class=muted>Карточки маркетплейса и внутренняя единица учёта</div></div><div><button class=btn onclick=addProduct()>+ Новый товар</button> <button class="btn light" onclick="exportProducts()">Выгрузить CSV</button></div></div><div class=filterbar><input class="wide" placeholder="Поиск по коду / товару / WB / баркоду" value="${esc(q)}" oninput="prodQ=this.value;products()"><button class="btn light" onclick="toast('Фильтр подготовлен')">☷ Фильтр</button><button class="btn light" onclick="toast('Колонки: можно расширить в следующем обновлении')">▥ Колонки</button></div><div class=grid style="margin-bottom:14px"><div class=kpi><small>Внутренних кодов</small><strong>${s.products.length}</strong></div><div class=kpi><small>С себестоимостью</small><strong>${s.products.filter(x=>x.cost>0).length}</strong></div><div class=kpi><small>Средняя себестоимость</small><strong>${money(s.products.reduce((a,x)=>a+x.cost,0)/(s.products.length||1))}</strong></div><div class=kpi><small>GTIN</small><strong>${s.products.filter(x=>x.gtin).length}</strong></div></div><div class=table-scroll><table class=wide-table><tr><th>Код / товар</th><th>Категория</th><th>Артикул WB</th><th>Баркод</th><th>Себестоимость</th><th>Цена</th><th>Скидка</th><th>GTIN</th><th></th></tr>${rows||'<tr><td colspan=9>Ничего не найдено</td></tr>'}</table></div>`}
function productForm(x={},edit=false){document.getElementById('app').innerHTML=`<div class=card><div class=hero><div><h2>${edit?'Карточка товара':'Новый товар'}</h2><div class=muted>Артикул CLARA — главный внутренний ключ</div></div><button class="btn light" onclick="show('products')">Назад</button></div><div class=form><div class=field><label>Артикул CLARA</label><input id=f_a value="${esc(x.article||'')}" ${edit?'disabled':''}></div><div class=field><label>Категория / предмет</label><input id=f_n value="${esc(x.name||'')}"></div><div class=field><label>Артикул WB</label><input id=f_wb value="${esc(x.wbArticle||'')}"></div><div class=field><label>Баркод</label><input id=f_bc value="${esc(x.barcode||'')}"></div><div class=field><label>Себестоимость ₽</label><input id=f_c type=number value="${x.cost||0}"></div><div class=field><label>Розничная цена ₽</label><input id=f_pr type=number value="${x.price||0}"></div><div class=field><label>Скидка продавца %</label><input id=f_d type=number value="${x.discount||0}"></div><div class=field><label>Состав / ткань</label><input id=f_comp value="${esc(x.composition||'')}" placeholder="100% хлопок"></div><div class=field><label>Цвета через запятую</label><input id=f_col value="${esc((x.colors||[]).join(', '))}" placeholder="чёрный, бежевый"></div><div class=field><label>Размеры через запятую</label><input id=f_sz value="${esc((x.sizes||[]).join(', '))}" placeholder="48, 50, 52, 54, 56, 58"></div><div class=field><label>GTIN</label><input id=f_gtin value="${esc(x.gtin||'')}"></div></div><p><button class=btn onclick="saveProductForm(${edit?'true':'false'})">Сохранить карточку</button></p></div>`}
function addProduct(){productForm()}function editProduct(a){productForm(p(a),true)}
function saveProductForm(edit){let a=f_a.value.trim();if(!a||!f_n.value.trim())return alert('Укажите артикул и категорию');let x={article:a,name:f_n.value.trim(),category:f_n.value.trim(),wbArticle:f_wb.value.trim(),barcode:f_bc.value.trim(),cost:+f_c.value||0,price:+f_pr.value||0,discount:+f_d.value||0,composition:f_comp.value.trim(),colors:f_col.value.split(',').map(x=>x.trim()).filter(Boolean),sizes:f_sz.value.split(',').map(x=>x.trim()).filter(Boolean),gtin:f_gtin.value.trim(),variants:[]};if(edit){let i=s.products.findIndex(z=>z.article===a);s.products[i]={...s.products[i],...x}}else s.products.push(x);toast('Карточка сохранена');show('products')}
function production(){let x=s.products[0]||{sizes:[],colors:[]};let rows=s.batches.map(b=>`<tr><td>${b.date}</td><td>${esc(b.article)}</td><td>${esc(b.color||'—')}</td><td><b>${b.qty}</b></td><td>${esc(b.breakdown||'—')}</td><td>${esc(b.note||'')}</td></tr>`).join('');document.getElementById('app').innerHTML=`<div class=hero><div><h2>Производство</h2><div class=muted>Произвели партию — сразу добавили готовые изделия на склад CLARA</div></div></div><div class=card><div class=form><div class=field><label>Товар</label><select id=ba onchange=renderProductionSizes()>${s.products.map(x=>`<option value="${esc(x.article)}">${esc(x.article)} — ${esc(x.name)}</option>`).join('')}</select></div><div class=field><label>Цвет</label><select id=bcolor>${(x.colors||[]).map(c=>`<option>${esc(c)}</option>`).join('')}<option value="">Другой цвет…</option></select></div></div><div class="card size-card"><div class=section-head><div><b>Количество по размерам</b><div class=muted>Не нужно заполнять все размеры. Оставляй ненужные размеры равными нулю.</div></div><div class=total-box>Итого: <b id=prodTotal>0</b> шт.</div></div><div id=sizeRows>${sizeRowsFor(x)}</div></div><div class=field style="margin-top:14px"><label>Комментарий к партии</label><input id=bnote placeholder="Например: партия 09.09.2026"></div><p><button class=btn onclick=createBatch()>Добавить на склад</button></p><div class=note>После нажатия остаток увеличится сразу. В движении сохранится разбивка по размерам.</div></div><div class=section-title>История производства</div><div class=table-scroll><table class=wide-table><tr><th>Дата</th><th>Артикул</th><th>Цвет</th><th>Количество</th><th>Размеры</th><th>Комментарий</th></tr>${rows||'<tr><td colspan=6>Партий пока нет</td></tr>'}</table></div>`;calcProductionTotal()}
function sizeRowsFor(x){return (x.sizes||[]).map((z,i)=>`<div class=size-row><div class=size-name>${esc(z)}</div><div class=size-dash>—</div><input class=size-qty id=sz_${i} data-size="${esc(z)}" type=number min=0 value=0 oninput=calcProductionTotal()><span>шт.</span></div>`).join('')||'<div class=muted>Добавьте размеры в карточку товара.</div>'}
function renderProductionSizes(){let x=p(ba.value)||{sizes:[],colors:[]};bcolor.innerHTML=(x.colors||[]).map(c=>`<option>${esc(c)}</option>`).join('')+'<option value="">Другой цвет…</option>';sizeRows.innerHTML=sizeRowsFor(x);calcProductionTotal()}function calcProductionTotal(){let total=[...document.querySelectorAll('.size-qty')].reduce((a,e)=>a+(+e.value||0),0);if(document.getElementById('prodTotal'))prodTotal.textContent=total}
function createBatch(){let inputs=[...document.querySelectorAll('.size-qty')],q=inputs.reduce((a,e)=>a+(+e.value||0),0);if(q<=0)return alert('Укажите количество хотя бы для одного размера');let breakdown=inputs.filter(e=>(+e.value||0)>0).map(e=>`${e.dataset.size}:${+e.value}`).join('; ');let date=new Date().toLocaleDateString('ru-RU');s.batches.push({date,article:ba.value,qty:q,color:bcolor.value,breakdown,note:bnote.value.trim()});s.movements.push({date:new Date().toLocaleString('ru-RU'),type:'production',article:ba.value,qty:q,ref:'Партия производства',color:bcolor.value,breakdown});toast(`Добавлено на склад: ${q} шт.`);show('production')}
function variantStock(article){let out={};(p(article)?.sizes||[]).forEach(z=>out[z]=0);s.movements.filter(m=>m.article===article).forEach(m=>{let sign=(m.type==='sale'||m.type==='toWB'||m.type==='writeoff')?-1:1;if(m.breakdown){m.breakdown.split(';').forEach(part=>{let [z,q]=part.split(':');if(z){z=z.trim();out[z]=(out[z]||0)+sign*(+q||0)}})}else if(m.size){out[m.size]=(out[m.size]||0)+sign*(m.qty||0)} });return out}
function showSizeStock(article){let x=p(article)||{};let by=variantStock(article);let rows=Object.entries(by).map(([z,q])=>`<tr><td><b>${esc(z)}</b></td><td><b>${q}</b></td><td>${q>0?'В наличии':q===0?'Нет остатка':'Проверить'}</td></tr>`).join('');let total=Object.values(by).reduce((a,b)=>a+b,0);let html=`<div class="modal-backdrop" onclick="closeModal(event)"><div class="modal" onclick="event.stopPropagation()"><div class="hero"><div><h2>Остатки по размерам</h2><div class="muted">${esc(article)} — ${esc(x.name||'')}</div></div><button class="btn light" onclick="closeModal()">Закрыть</button></div><div class="grid"><div class="kpi"><small>Общий остаток</small><strong>${total} шт.</strong></div><div class="kpi"><small>Размеров</small><strong>${Object.keys(by).length}</strong></div><div class="kpi"><small>Цвета</small><strong>${(x.colors||[]).length}</strong></div></div><div class="table-scroll"><table class="wide-table"><tr><th>Размер</th><th>Остаток</th><th>Статус</th></tr>${rows||'<tr><td colspan="3">Размеры не указаны</td></tr>'}</table></div><p class="note">Здесь CLARA показывает остаток отдельно по каждому размеру. В следующих версиях можно будет раскрывать также цвет и историю движений по каждому размеру.</p></div></div>`;let el=document.createElement('div');el.id='modalRoot';el.innerHTML=html;document.body.appendChild(el)}
function closeModal(e){if(e&&e.target&&e.target.className!=='modal-backdrop')return;document.getElementById('modalRoot')?.remove()}
function warehouse(){let by=stockByArticle();let rows=Object.entries(by).map(([a,q])=>`<tr class="clickable-row" onclick="showSizeStock('${esc(a)}')"><td><b>${esc(a)}</b></td><td>${esc(p(a)?.name||'')}</td><td class=${q<0?'bad':'ok'}>${q}</td><td>${esc(p(a)?.colors?.join(', ')||'—')}</td><td><button class="btn light" onclick="event.stopPropagation();showSizeStock('${esc(a)}')">Все размеры</button></td></tr>`).join('');let reserved=s.movements.filter(m=>m.type==='reserveFBS').reduce((a,m)=>a+m.qty,0);document.getElementById('app').innerHTML=`<div class=hero><div><h2>Склад CLARA</h2><div class=muted>Приходы, FBS-резерв, отгрузки, продажи и списания</div></div><button class="btn light" onclick="exportWarehouse()">Выгрузить CSV</button></div><div class=grid><div class=kpi><small>На внутреннем складе</small><strong>${Math.max(0,stockTotal())} шт.</strong></div><div class=kpi><small>Резерв FBS</small><strong>${reserved} шт.</strong></div><div class=kpi><small>КИЗ в CLARA</small><strong>${s.kiz.length}</strong></div><div class=kpi><small>Ошибки маркировки</small><strong>${s.kiz.filter(k=>k.status==='Ошибка').length}</strong></div></div><div class=section-title>Остатки по товарам</div><div class=table-scroll><table class=wide-table><tr><th>Артикул</th><th>Товар</th><th>Остаток</th><th>Цвета</th><th>Размеры</th></tr>${rows||'<tr><td colspan=5>Нет движений</td></tr>'}</table></div><div class=note style="margin-top:10px">Нажми на строку товара или кнопку «Все размеры», чтобы открыть подробный остаток по каждому размеру.</div><div class=section-title>Последние движения</div><div class=table-scroll><table class=wide-table><tr><th>Дата</th><th>Тип</th><th>Артикул</th><th>Кол-во</th><th>Ссылка</th><th>Размеры</th></tr>${s.movements.slice().reverse().slice(0,30).map(m=>`<tr><td>${esc(m.date)}</td><td>${esc(m.type)}</td><td>${esc(m.article)}</td><td>${m.qty}</td><td>${esc(m.ref||'')}</td><td>${esc(m.breakdown||'')}</td></tr>`).join('')||'<tr><td colspan=6>Движений пока нет</td></tr>'}</table></div>`}

function seedOrder(){
  let x=s.products[0]||{};
  let size=(x.sizes&&x.sizes[2])||'52';
  let o={id:'571'+Date.now().toString().slice(-7),article:x.article,name:x.name,size,color:(x.colors&&x.colors[0])||'чёрный',status:'Новый',barcode:x.barcode||('0468'+Date.now().toString().slice(-8)),gtin:x.gtin||'',stickerCode:'',stickerPrinted:false,kiz:null,createdAt:new Date().toLocaleString('ru-RU')};
  s.orders.unshift(o);s.selectedOrder=o.id;save();fbs();toast('Тестовый FBS-заказ добавлен');
}
function fbs(){
  let tab=window.fbsTab||'new';
  document.getElementById('app').innerHTML=`
  <div class="hero"><div><h2>FBS — сборка заказов</h2><div class="muted">Сканирование товара → автоматический выбор заказа → автопечать стикера → скан стикера → КИЗ</div></div><div class="toolbar"><button class="btn" onclick="seedOrder()">+ Тестовый заказ</button><button class="btn light" onclick="fbsSettings()">⚙ Принтер</button></div></div>
  <div class="tabs fbs-tabs">
    <button class="tab ${tab==='new'?'active':''}" onclick="fbsTab('new')">Новые заказы <b>(${s.orders.filter(o=>!['Готов к отгрузке','Отменён','Отгружен'].includes(o.status)).length})</b></button>
    <button class="tab ${tab==='pick'?'active':''}" onclick="fbsTab('pick')">Лист подбора</button>
    <button class="tab ${tab==='pack'?'active':''}" onclick="fbsTab('pack')">Сборка поставки</button>
    <button class="tab ${tab==='supplies'?'active':''}" onclick="fbsTab('supplies')">Управление поставками</button>
  </div>${tab==='new'?fbsNew():tab==='pick'?fbsPick():tab==='pack'?fbsPack():fbsSupplies()}`;
}
function fbsTab(k){window.fbsTab=k;fbs()}
function fbsNew(){
  let pending=s.orders.filter(o=>!['Готов к отгрузке','Отменён','Отгружен'].includes(o.status));
  let rows=pending.map(o=>`<tr><td><input type="checkbox" ${o.selected?'checked':''} onchange="toggleOrder('${esc(o.id)}')"></td><td><b>${esc(o.id)}</b><br><small>${esc(o.createdAt||'')}</small></td><td>${esc(o.name||'—')}</td><td><b>${esc(o.size||'—')}</b></td><td>${esc(o.article||'—')}</td><td>${esc(o.barcode||'—')}</td><td><span class="tag">${esc(o.status)}</span></td><td><button class="btn light" onclick="orderMenu('${esc(o.id)}')">⋮</button></td></tr>`).join('');
  return `<div class="card fbs-workbar"><button class="btn" onclick="refreshFbs()">Обновить</button><input id="fbsProductScan" class="scan" placeholder="Сканируйте GTIN или баркод товара — заказ найдётся автоматически" autofocus onkeydown="if(event.key==='Enter')handleProductScan(this.value)"><select id="fbsWarehouse"><option>Все склады</option><option>Мой склад CLARA</option><option>Склад WB</option></select><div class="fbs-counter"><b>Всего заказов: ${pending.length}</b> <span>На складе: ${pending.filter(o=>hasStock(o)).length}</span></div></div><div class="card"><div class="section-head"><b>Новые заказы</b><span class="muted">Сканируйте товар — CLARA сама выберет подходящий заказ и отправит стикер на принтер.</span></div><div class="table-scroll"><table class="wide-table"><tr><th></th><th>№ заказа</th><th>Товар</th><th>Размер</th><th>Артикул</th><th>Баркод</th><th>Статус</th><th></th></tr>${rows||'<tr><td colspan="8" class="muted">Новых заказов нет</td></tr>'}</table></div></div>`;
}
function fbsPick(){
 let selected=s.orders.filter(o=>o.selected&&o.status!=='Готов к отгрузке');
 return `<div class="card"><div class="filterbar"><select id="pickFilter"><option>Новые заказы</option><option>Новые заказы (отмеченные)</option><option>Новые заказы (из запаса)</option><option>Поставка от ${new Date().toLocaleDateString('ru-RU')}</option></select><button class="btn" onclick="confirmPick()">Подтвердить</button></div><div class="grid"><div class="kpi"><small>Выбрано</small><strong>${selected.length}</strong></div><div class="kpi"><small>В наличии</small><strong>${selected.filter(hasStock).length}</strong></div><div class="kpi"><small>Стикеры напечатаны</small><strong>${s.orders.filter(o=>o.stickerPrinted).length}</strong></div><div class="kpi"><small>Готово</small><strong>${s.orders.filter(o=>o.status==='Готов к отгрузке').length}</strong></div></div><div class="table-scroll" style="margin-top:14px"><table class="wide-table"><tr><th>Заказ</th><th>Товар</th><th>Размер</th><th>Склад</th><th>Статус</th></tr>${selected.map(o=>`<tr><td>${esc(o.id)}</td><td>${esc(o.name)}</td><td>${esc(o.size)}</td><td>${hasStock(o)?'Есть':'Нет'}</td><td>${esc(o.status)}</td></tr>`).join('')||'<tr><td colspan="5" class="muted">Отметьте заказы в «Новых заказах».</td></tr>'}</table></div></div>`;
}
function fbsPack(){
 let active=s.orders.filter(o=>['Стикер сформирован','Стикер напечатан','Ожидает КИЗ'].includes(o.status));
 let o=s.orders.find(x=>x.id===s.selectedOrder)||active[0];
 return `<div class="fbs-pack-grid"><div class="card"><div class="fbs-machine"><div class="machine-step active">1<br><b>Скан товара</b></div><div class="machine-line"></div><div class="machine-step ${o&&o.stickerPrinted?'active':''}">2<br><b>Стикер</b></div><div class="machine-line"></div><div class="machine-step ${o&&o.kiz?'active':''}">3<br><b>КИЗ</b></div><div class="machine-line"></div><div class="machine-step ${o&&o.status==='Готов к отгрузке'?'active':''}">4<br><b>Готово</b></div></div><input id="packScan" class="scan big-scan" autofocus placeholder="Сканируйте GTIN / баркод товара" onkeydown="if(event.key==='Enter')handlePackScan(this.value)"><div id="packMessage" class="pack-message">Готов к сканированию товара</div></div><div class="card">${o?packOrderCard(o):`<div class="empty-state"><b>Заказ не выбран</b><p>Сканируйте товар. CLARA найдёт ближайший подходящий заказ.</p></div>`}</div></div>`;
}
function packOrderCard(o){return `<div class="pack-order"><div class="order-top"><div><small>Заказ</small><h2>${esc(o.id)}</h2></div><span class="tag">${esc(o.status)}</span></div><div class="product-preview"><div class="product-placeholder">CLARA</div><div><b>${esc(o.name)}</b><p>Артикул: ${esc(o.article)}</p><p>Размер: <strong>${esc(o.size)}</strong> · Цвет: ${esc(o.color||'—')}</p><p>Баркод: ${esc(o.barcode||'—')}</p></div></div><div class="workflow-status"><div class="status-row ${o.stickerPrinted?'done':''}"><span>✓</span><b>Стикер заказа</b><small>${o.stickerPrinted?'Напечатан автоматически':'Ожидает печати'}</small></div><div class="status-row ${o.kiz?'done':''}"><span>✓</span><b>Честный ЗНАК</b><small>${o.kiz?'КИЗ привязан':'После сканирования стикера сканируйте КИЗ'}</small></div><div class="status-row ${o.status==='Готов к отгрузке'?'done':''}"><span>✓</span><b>Сборка</b><small>${o.status==='Готов к отгрузке'?'Готов к отгрузке':'В работе'}</small></div></div><div class="scan-chain"><label>Скан стикера заказа</label><input id="stickerScan" class="scan" autofocus placeholder="Сканируйте стикер после печати" onkeydown="if(event.key==='Enter')handleStickerScan(this.value)"><label style="margin-top:12px">Скан КИЗ</label><input id="kizScan" class="scan" placeholder="Сканируйте КИЗ после стикера" ${o.kiz?'disabled':''} onkeydown="if(event.key==='Enter')handleKizScanV4(this.value,'${esc(o.id)}')"></div></div>`}
function fbsSupplies(){let ready=s.orders.filter(o=>o.status==='Готов к отгрузке').length;return `<div class="grid"><div class="kpi"><small>Готово к отгрузке</small><strong>${ready}</strong></div><div class="kpi"><small>В сборке</small><strong>${s.orders.filter(o=>['Стикер напечатан','Ожидает КИЗ'].includes(o.status)).length}</strong></div><div class="kpi"><small>Ошибки</small><strong>${s.orders.filter(o=>o.status==='Ошибка').length}</strong></div><div class="kpi"><small>Всего заказов</small><strong>${s.orders.length}</strong></div></div><div class="card" style="margin-top:14px"><div class="section-head"><b>Текущая поставка</b><button class="btn" onclick="toast('После подключения WB API поставка будет создаваться и обновляться автоматически')">Обновить из WB</button></div><table><tr><th>Заказ</th><th>Артикул</th><th>Размер</th><th>КИЗ</th><th>Статус</th></tr>${s.orders.filter(o=>o.status==='Готов к отгрузке').map(o=>`<tr><td>${esc(o.id)}</td><td>${esc(o.article)}</td><td>${esc(o.size)}</td><td>${esc(o.kiz||'—')}</td><td class="ok">Готов к отгрузке</td></tr>`).join('')||'<tr><td colspan="5" class="muted">Готовых заказов пока нет.</td></tr>'}</table></div>`}
function hasStock(o){return stockByArticle()[o.article]>0}
function toggleOrder(id){let o=s.orders.find(x=>x.id===id);if(o)o.selected=!o.selected;save()}
function confirmPick(){s.orders.filter(o=>o.selected&&o.status==='Новый').forEach(o=>o.status='В листе подбора');save();toast('Заказы добавлены в лист подбора');fbs()}
function refreshFbs(){toast('Лента FBS обновлена');fbs()}
function handleProductScan(v){let code=v.trim();if(!code)return;let candidates=s.orders.filter(o=>!['Готов к отгрузке','Отменён','Отгружен'].includes(o.status)&&(o.barcode===code||o.gtin===code||p(o.article)?.barcode===code||p(o.article)?.gtin===code));if(!candidates.length){toast('Заказ по этому GTIN/баркоду не найден');return}let o=candidates.sort((a,b)=>String(a.createdAt).localeCompare(String(b.createdAt)))[0];startPacking(o)}
function handlePackScan(v){handleProductScan(v);}
function startPacking(o){s.selectedOrder=o.id;o.status='Стикер сформирован';o.stickerCode=o.stickerCode||('ST-'+o.id);save();fbsTab('pack');setTimeout(()=>autoPrintSticker(o.id),80)}
function handleStickerScan(v){let code=v.trim();if(!code)return;let o=s.orders.find(x=>x.id===code||x.stickerCode===code||x.barcode===code);if(!o){toast('Стикер не найден');return}s.selectedOrder=o.id;o.status='Ожидает КИЗ';save();fbs();setTimeout(()=>document.getElementById('kizScan')?.focus(),80);toast('Стикер подтверждён — сканируйте КИЗ')}
function handleKizScanV4(v,id){let code=v.trim();if(!code)return;let o=s.orders.find(x=>x.id===id),existing=s.kiz.find(k=>k.code===code);if(!o)return;if(existing&&existing.orderId!==id){o.status='Ошибка';save();toast('Ошибка: КИЗ уже используется в другом заказе');fbs();return}let k=existing||{code,status:'Зарезервирован FBS',orderId:id,article:o.article,date:new Date().toLocaleString('ru-RU')};if(!existing)s.kiz.push(k);k.status='Зарезервирован FBS';k.orderId=id;o.kiz=code;o.status='Готов к отгрузке';s.movements.push({date:new Date().toLocaleString('ru-RU'),type:'reserveFBS',article:o.article,qty:1,ref:id,kiz:code,size:o.size});save();toast('КИЗ привязан — заказ готов к отгрузке');fbsTab('pack')}
function autoPrintSticker(id){let o=s.orders.find(x=>x.id===id);if(!o)return;let payload={type:'wb-fbs-sticker',orderId:o.id,barcode:o.barcode,article:o.article,size:o.size,color:o.color,format:'58x40'};o.stickerPrinted=true;o.status='Стикер напечатан';o.printedAt=new Date().toLocaleString('ru-RU');save();fetch((s.settings.printAgentUrl||'http://127.0.0.1:17890')+'/print',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}).then(r=>{if(!r.ok)throw new Error();toast('Стикер отправлен на принтер 58×40');}).catch(()=>{toast('Принтер-агент не подключён — открываю резервную печать');printStickerFallback(o.id)}).finally(()=>{fbs();setTimeout(()=>document.getElementById('stickerScan')?.focus(),150)})}
function printStickerFallback(id){let o=s.orders.find(x=>x.id===id);if(!o)return;let w=window.open('','_blank','width=500,height=400');w.document.write(`<html><head><title>FBS ${esc(o.id)}</title><style>@page{size:58mm 40mm;margin:0}body{margin:0;width:58mm;height:40mm;font:9px Arial;padding:2mm;box-sizing:border-box}b{font-size:11px}</style></head><body><b>WILDBERRIES FBS</b><br>Заказ: ${esc(o.id)}<br>Арт.: ${esc(o.article)}<br>Размер: ${esc(o.size)}<br>ШК: ${esc(o.barcode||'')}<br><br><b>ST-${esc(o.id)}</b></body></html>`);w.document.close();w.focus();w.print()}
function fbsSettings(){document.getElementById('app').innerHTML=`<div class="card"><div class="hero"><div><h2>Настройки печати FBS</h2><div class="muted">Принтер получает стикер автоматически после сканирования товара.</div></div><button class="btn light" onclick="fbs()">Назад</button></div><div class="form"><div class="field"><label>Размер стикера</label><select disabled><option>58 × 40 мм</option></select></div><div class="field"><label>Принтер</label><input value="Принтер по умолчанию Windows" disabled></div><div class="field"><label>Local Print Agent</label><input id="printUrl" value="${esc(s.settings.printAgentUrl||'http://127.0.0.1:17890')}" placeholder="http://127.0.0.1:17890"></div><div class="field"><label>Режим</label><select disabled><option>Автоматическая печать без кнопки</option></select></div></div><p class="note">Для настоящей печати без диалога браузера нужен локальный Print Agent на компьютере со сканером и принтером. CLARA уже подготовлена к этому контуру.</p><button class="btn" onclick="savePrintSettings()">Сохранить</button> <button class="btn light" onclick="testPrintAgent()">Тест принтера</button></div>`}
function savePrintSettings(){s.settings.printAgentUrl=(document.getElementById('printUrl').value||'http://127.0.0.1:17890').replace(/\/$/,'');save();toast('Настройки принтера сохранены');fbs()}
function testPrintAgent(){fetch((s.settings.printAgentUrl||'http://127.0.0.1:17890')+'/test',{method:'POST'}).then(()=>toast('Тест отправлен на принтер')).catch(()=>toast('Print Agent не найден'))}
function orderMenu(id){let o=s.orders.find(x=>x.id===id);if(!o)return;let a=prompt('Действие: 1 — добавить в поставку, 2 — печать стикера, 3 — сборка', '1');if(a==='1'){o.selected=true;o.status='В листе подбора';save();fbs()}else if(a==='2')autoPrintSticker(id);else if(a==='3')startPacking(o)}
function analytics(){let section=window.analyticsSection||'analytics';document.getElementById('app').innerHTML=`<div class="analytics-layout"><div class="analytics-side"><h4>Аналитика продаж</h4>${[['analytics','Аналитика'],['ordersFeed','Лента заказов'],['ordersMap','Карта заказов'],['ads','Реклама'],['adsDays','Реклама · Дни'],['competitors','Конкуренты'],['search','Поисковые запросы'],['unitA','Unit-экономика'],['logistics','Коэффициенты логистики'],['journal','Журнал товара'],['goods','Товары'],['cost','Себестоимость']].map(([k,n])=>`<button class="${section===k?'active':''}" onclick="analyticsSection('${k}')">${n}</button>`).join('')}</div><div class="analytics-main">${analyticsContent(section)}</div></div>`}
function analyticsSection(k){window.analyticsSection=k;analytics()}
function setPlatform(v){window.analyticsPlatform=v;toast(v==='WB'?'Выбрано Wildberries':'Выбран Ozon');analytics()}
function setMetric(el){document.querySelectorAll('.metric').forEach(x=>x.classList.remove('active'));el.classList.add('active');toast('Показатель: '+el.textContent)}
function toggleForecast(el){el.classList.toggle('active');toast(el.classList.contains('active')?'Прогноз/факт включён':'Прогноз/факт выключен')}
function analyticsHeader(subtitle){let wb=(window.analyticsPlatform||'WB')==='WB';return `<div class="hero"><div><h2>${subtitle}</h2><div class="muted">Единый аналитический контур CLARA • ${wb?'Wildberries':'Ozon'}</div></div><div class="seg"><button class="btn ${wb?'purple':''} ${!wb?'light':''}" onclick="setPlatform('WB')">WB</button><button class="btn ${!wb?'purple':''} ${wb?'light':''}" onclick="setPlatform('Ozon')">Ozon</button></div></div>`}
function dateControls(){return `<div class="filterbar"><button class="tab ${window.analyticsPeriod!=='period'?'active':''}" onclick="window.analyticsPeriod='month';analytics()">Месяц</button><button class="tab ${window.analyticsPeriod==='period'?'active':''}" onclick="window.analyticsPeriod='period';analytics()">Период</button><select><option>2026</option></select><select><option>Сентябрь</option><option>Август</option><option>Июль</option></select><select><option>Заказы ₽</option><option>Заказы шт</option><option>Продажи ₽</option><option>Выкуп %</option><option>Остаток</option><option>Дни хватит</option><option>ДРР %</option></select><select class="wide"><option>Магазин: все</option></select><select class="wide"><option>Бренд: все</option></select><select class="wide"><option>Категория: все</option></select><input class="wide" placeholder="Артикул, название или nmId..."><label><input type=checkbox style="width:auto"> Учитывать % выкупа</label><button class="btn ${window.forecastOn?'':'light'}" onclick="window.forecastOn=!window.forecastOn;analytics()">↗ Прогноз/Факт</button><button class="btn light" onclick="toast('Табличный режим включён')">☷ Таблица</button><button class="btn light" onclick="toast('Выбор показателей открыт')">Показатели (12) ▾</button><button class="btn light" onclick="exportAnalytics()">▧ Excel</button></div>`}
function exportAnalytics(){let rows=[['Показатель','Значение'],['Заказы, шт',s.orders.length],['Продажи, шт',s.movements.filter(m=>m.type==='sale').reduce((a,m)=>a+m.qty,0)],['СПП %',pc(s.settings.spp)],['КВВ %',pc(s.settings.commission)]];download('CLARA_аналитика.csv',csv(rows));toast('Аналитика выгружена')}
function analyticsMain(){let sold=s.movements.filter(m=>m.type==='sale').reduce((a,m)=>a+m.qty,0),orders=s.orders.length;let metrics=['Заказы ₽','Заказы шт','Продажи ₽','Продажи шт','СПП %','Отказы','Выкуплено','Реклама ₽','ДРР %','Маржа по заказам ₽ — прогноз','Маржа по заказам ₽ — факт','Маржа по продажам ₽'];return analyticsHeader('Аналитика')+dateControls()+`<div class=card><div class=section-head><b>Динамика по дням</b><span class=muted>${window.forecastOn?'Режим прогноз / факт':'Товар = строка, сверху итоговая строка'}</span></div><div class=metric-pills>${metrics.map((x,i)=>`<button onclick="setMetric(this)" class="metric ${i<4?'active':''}">${x}</button>`).join('')}</div><div class=table-scroll><table class=wide-table><tr><th>Фото</th><th>Артикул</th><th>Показатель</th><th>Прогноз</th><th>Факт</th><th>Зн</th><th>2н</th><th>1н</th><th>Дин.</th><th>01.09</th><th>02.09</th><th>03.09</th><th>04.09</th><th>05.09</th><th>06.09</th><th>07.09</th></tr><tr><td>Σ</td><td><b>ИТОГО</b><br><small>${s.products.length} арт.</small></td><td>${metrics.map(x=>`<div style="padding:4px 0">${x}</div>`).join('')}</td><td>${orders}<br>—<br>${pc(s.settings.spp)}<br>—<br>—<br>${sold}</td><td>${orders}<br>—<br>${pc(s.settings.spp)}<br>—<br>—<br>${sold}</td><td>—</td><td>—</td><td>—</td><td>—</td><td colspan=7 class=muted>Данные по дням заполнятся после WB API / импорта отчёта</td></tr></table></div></div>`}
function ordersFeed(){return analyticsHeader('Лента заказов')+`<div class=tabs><button class="tab active" onclick="toast('Лента заказов')">Лента</button><button class=tab onclick="toast('Статистика заказов')">Статистика</button><button class=tab onclick="setPlatform('WB')">Все площадки</button><button class="tab active" onclick="setPlatform('WB')">Wildberries</button><button class=tab onclick="setPlatform('Ozon')">Ozon</button><button class=tab>Все модели</button><button class=tab>FBO</button><button class=tab>FBS</button></div><div class=filterbar><select><option>Все магазины</option></select><select><option>Все склады</option></select><select><option>Все округа</option></select><input type=date><input type=date><button class=tab onclick="toast('Период: сегодня')">Сегодня</button><button class=tab>7</button><button class=tab>14</button><button class=tab>30</button><button class="tab active">Всё</button><input id=orderSearch class=wide placeholder="Товар / артикул / бренд"><button class=btn onclick="filterOrders()">Найти</button></div><div class=grid3><div class=kpi><small>Заказы сегодня</small><strong>${s.orders.length} шт · 0 ₽</strong></div><div class=kpi><small>Темп к этому часу</small><strong>—</strong></div><div class=kpi><small>Вчера всего</small><strong>0 шт · 0 ₽</strong></div></div><div class=card style="margin-top:15px"><div class=muted>${s.orders.length?'Заказы CLARA':'Нет заказов под выбранные фильтры'}</div><div id=ordersList>${s.orders.map(o=>`<div class=order data-order="${esc(o.id+' '+o.article+' '+o.name+' '+o.size+' '+o.color)}"><b>${esc(o.id)}</b> <span class=tag>${esc(o.status)}</span><br>${esc(o.article)} · ${esc(o.name)} · ${esc(o.size)} · ${esc(o.color)}</div>`).join('')}</div></div>`}
function filterOrders(){let q=(document.getElementById('orderSearch')?.value||'').toLowerCase();document.querySelectorAll('[data-order]').forEach(e=>e.style.display=e.dataset.order.toLowerCase().includes(q)?'':'none');toast(q?'Фильтр применён':'Показаны все заказы')}
function ordersMap(){let points=[[25,48],[38,35],[49,55],[61,44],[72,60],[82,38]];return analyticsHeader('Карта заказов')+`<div class=tabs><button class="tab active">Все площадки</button><button class=tab onclick="setPlatform('WB')">Wildberries</button><button class=tab onclick="setPlatform('Ozon')">Ozon</button><button class="tab active">Все модели</button><button class=tab>FBO</button><button class=tab>FBS</button><select class=wide><option>Все магазины</option></select><select class=wide><option>Все склады</option></select><select><option>Все округа</option></select><button class="tab active">30 дней</button></div><div class=grid><div class=kpi><small>Заказы по России</small><strong>${s.orders.length} шт</strong><small>0 ₽</small></div><div class=kpi><small>Регионов с заказами</small><strong>${s.orders.length?1:0}</strong><small>из 85 субъектов</small></div><div class=kpi><small>Топ-3 региона</small><strong>${s.orders.length?'—':'—'}</strong></div><div class=kpi><small>Выкуп по России</small><strong>0,0%</strong><small>0 шт выкуплено</small></div></div><div class=card style="margin-top:15px"><div class=map>${points.map(([x,y])=>`<i class=dot style="left:${x}%;top:${y}%"></i>`).join('')}</div><p class=note>После загрузки заказов карта показывает распределение заказов и выкупов по регионам России.</p></div>`}
function reports(){let sold=s.movements.filter(m=>m.type==='sale').reduce((a,m)=>a+m.qty,0),prod=s.batches.reduce((a,b)=>a+b.qty,0);document.getElementById('app').innerHTML=`<div class=hero><div><h2>Отчёты</h2><div class=muted>Продажи, производство, склад, КИЗ и финансовый контур</div></div><button class="btn light" onclick="toast('Выгрузка подготовлена')">Выгрузить CSV</button></div><div class=grid><div class=kpi><small>Произведено</small><strong>${prod} шт.</strong></div><div class=kpi><small>Продано</small><strong>${sold} шт.</strong></div><div class=kpi><small>FBS заказов</small><strong>${s.orders.length}</strong></div><div class=kpi><small>КИЗ</small><strong>${s.kiz.length}</strong></div></div><div class=grid3 style="margin-top:15px"><div class=card><b>Продажи</b><p class=note>Заказы, продажи, выкуп, возвраты, динамика и регионы.</p></div><div class=card><b>Прибыль</b><p class=note>Выручка → КВВ → логистика → реклама → налог → себестоимость → чистая прибыль.</p></div><div class=card><b>Производство</b><p class=note>Сколько произведено и какой остаток по артикулам/размерам.</p></div></div>`}
function settings(){let x=s.settings;document.getElementById('app').innerHTML=`<div class=hero><div><h2>Настройки</h2><div class=muted>Общие параметры расчёта и подготовка API</div></div></div><div class=tabs><button class="tab active">Общие</button><button class=tab>Уведомления</button><button class=tab>Безопасность</button><button class=tab>API</button><button class=tab>Подключения</button><button class=tab>Интеграции</button></div><div class=grid3><div class=card><h3>Unit-экономика</h3><div class=form>${[['СПП','spp'],['Комиссия WB','commission'],['Эквайринг','acq'],['ДРР','ads'],['Налог','tax'],['Выкуп','buyout'],['Логистика','logistics']].map(([n,k])=>`<div class=field><label>${n} %</label><input id=i_${k} type=number step=.1 value="${(x[k]*100).toFixed(1)}"></div>`).join('')}<div class=field><label>Возвратная логистика ₽</label><input id=i_return type=number value="${x.returnLogistics}"></div></div><p><button class=btn onclick=saveSettings()>Сохранить</button></p></div><div class=card><h3>Wildberries API</h3><p class=note>Вставлять токен сюда пока не требуется. На следующем этапе сервер будет принимать токен защищённо и получать данные WB.</p><button class="btn" onclick="toast('Серверный API-контур будет подключён после завершения интерфейса V3')">Подключить ключ</button></div><div class=card><h3>Честный ЗНАК API</h3><p class=note>Подготовлены операции: ввод в оборот, вывод, возврат, проверка КИЗ, документы и УПД.</p><button class="btn light" onclick="show('mark')">Открыть ЧЗ</button></div></div>`}
function saveSettings(){['spp','commission','acq','ads','tax','buyout','logistics'].forEach(k=>s.settings[k]=+document.getElementById('i_'+k).value/100);s.settings.returnLogistics=+i_return.value||0;save();toast('Настройки сохранены');show('settings')}
function csv(rows){return rows.map(r=>r.map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(';')).join('\n')}
function download(name,text){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+text],{type:'text/csv;charset=utf-8'}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function exportProducts(){download('CLARA_товары.csv',csv([['Артикул','Название','WB','Баркод','Себестоимость','Цена','Скидка','GTIN'],...s.products.map(x=>[x.article,x.name,x.wbArticle,x.barcode,x.cost,x.price,x.discount,x.gtin])]))}function exportWarehouse(){download('CLARA_склад.csv',csv([['Артикул','Товар','Остаток'],...Object.entries(stockByArticle()).map(([a,q])=>[a,p(a)?.name,q])]))}function exportKiz(){download('CLARA_KIZ.csv',csv([['КИЗ','Артикул','FBS','Статус','Дата'],...s.kiz.map(k=>[k.code,k.article,k.orderId,k.status,k.date])]))}
show('home');
