const KEY='clara_v2';
const old=JSON.parse(localStorage.getItem('clara_v2')||'null');
let s=old||{products:INITIAL_PRODUCTS,batches:[],movements:[],orders:[],kiz:[],settings:{spp:.2578,commission:.435,acq:.04,ads:.05,tax:.06,buyout:.60,logistics:.25,returnLogistics:50},selectedOrder:null};
if(!s.products?.length)s.products=INITIAL_PRODUCTS;
function save(){localStorage.setItem(KEY,JSON.stringify(s))} function money(x){return Math.round(x||0).toLocaleString('ru-RU')+' ₽'} function pc(x){return ((x||0)*100).toFixed(1)+'%'} function p(a){return s.products.find(x=>x.article===a)}
const titles={home:'Главная',products:'Товары',production:'Производство',warehouse:'Склад',wb:'Wildberries',fbs:'FBS — сборка',mark:'Честный ЗНАК',analytics:'Аналитика продаж',unit:'Юнит-экономика',reports:'Отчёты',settings:'Настройки'};
function show(page){document.getElementById('title').textContent=titles[page];document.getElementById('crumb').textContent='CLARA / '+titles[page];document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.getAttribute('onclick')?.includes("'"+page+"'")));({home,products,production,warehouse,wb,fbs,mark,analytics,unit,reports,settings}[page])();save()}
function toast(t){const e=document.getElementById('toast');e.textContent=t;e.className='toast';setTimeout(()=>e.className='',2200)}
function stockTotal(){return s.movements.reduce((a,m)=>a+m.qty,0)}
function home(){let made=s.batches.reduce((a,b)=>a+b.qty,0), sent=s.movements.filter(m=>m.type==='toWB').reduce((a,m)=>a+m.qty,0), sold=s.movements.filter(m=>m.type==='sale').reduce((a,m)=>a+m.qty,0), reserved=s.orders.filter(o=>!['Отгружен','Отменён'].includes(o.status)).length;document.getElementById('app').innerHTML=`<div class=hero><div><h2>Добро пожаловать в CLARA</h2><div class=muted>Рабочий контур: товар → производство → склад → FBS → КИЗ → WB</div></div><button class=btn onclick="show('fbs')">Открыть сборку FBS</button></div><div class=grid><div class=card><small>Артикулов</small><div class=num>${s.products.length}</div></div><div class=card><small>Произведено</small><div class=num>${made} шт.</div></div><div class=card><small>Внутренний склад</small><div class=num>${Math.max(0,stockTotal())} шт.</div></div><div class=card><small>FBS в работе</small><div class=num>${reserved}</div></div></div><div class=grid style="margin-top:14px"><div class=card><small>Отправлено на WB</small><div class=num>${sent}</div></div><div class=card><small>Продано</small><div class=num>${sold}</div></div><div class=card><small>СПП</small><div class=num>${pc(s.settings.spp)}</div></div><div class=card><small>КВВ</small><div class=num>${pc(s.settings.commission)}</div></div></div><div class=card style="margin-top:18px"><b>Что уже заложено в V2</b><p class=note>Карточка товара с WB-артикулом и баркодом, цвета/размеры, партии производства, движения склада, FBS-заказы, сценарий сканирования, КИЗ и журнал операций Честного ЗНАКа. Реальные API WB/ЧЗ подключаются серверной частью.</p></div>`}
function products(){let q=(window.prodQ||'').toLowerCase();let rows=s.products.filter(x=>(x.article+x.name+x.wbArticle).toLowerCase().includes(q)).map(x=>`<tr><td><b>${x.article}</b></td><td>${x.name}</td><td>${x.wbArticle||'—'}</td><td>${x.barcode||'—'}</td><td>${money(x.cost)}</td><td>${money(x.price)}</td><td>${x.discount||0}%</td><td><button class="btn light" onclick="editProduct('${x.article}')">Открыть</button></td></tr>`).join('');document.getElementById('app').innerHTML=`<div class=toolbar><button class=btn onclick=addProduct()>+ Новый товар</button><input class=search placeholder="Поиск: артикул, WB, баркод" value="${q}" oninput="prodQ=this.value;products()"></div><table><tr><th>Артикул</th><th>Категория</th><th>Артикул WB</th><th>Баркод</th><th>Себестоимость</th><th>Цена</th><th>Скидка</th><th></th></tr>${rows}</table>`}
function productForm(x={},edit=false){document.getElementById('app').innerHTML=`<div class=card><div class=hero><div><h2>${edit?'Карточка товара':'Новый товар'}</h2><div class=muted>Основная единица учёта CLARA</div></div></div><div class=form><div class=field><label>Артикул CLARA</label><input id=f_a value="${x.article||''}" ${edit?'disabled':''}></div><div class=field><label>Категория / предмет</label><input id=f_n value="${x.name||''}"></div><div class=field><label>Артикул WB</label><input id=f_wb value="${x.wbArticle||''}"></div><div class=field><label>Баркод</label><input id=f_bc value="${x.barcode||''}"></div><div class=field><label>Себестоимость ₽</label><input id=f_c type=number value="${x.cost||0}"></div><div class=field><label>Розничная цена ₽</label><input id=f_pr type=number value="${x.price||0}"></div><div class=field><label>Скидка %</label><input id=f_d type=number value="${x.discount||0}"></div><div class=field><label>Цвета через запятую</label><input id=f_col value="${(x.colors||[]).join(', ')}" placeholder="чёрный, белый, бежевый"></div><div class=field><label>Размеры через запятую</label><input id=f_sz value="${(x.sizes||[]).join(', ')}" placeholder="48, 50, 52, 54, 56, 58"></div><div class=field><label>GTIN</label><input id=f_gtin value="${x.gtin||''}"></div></div><p><button class=btn onclick="saveProductForm(${edit?'true':'false'})">Сохранить карточку</button> <button class="btn light" onclick="show('products')">Назад</button></p></div>`}
function addProduct(){productForm()} function editProduct(a){productForm(p(a),true)}
function saveProductForm(edit){let a=f_a.value.trim();if(!a||!f_n.value.trim())return alert('Укажите артикул и категорию');let x={article:a,name:f_n.value.trim(),category:f_n.value.trim(),wbArticle:f_wb.value.trim(),barcode:f_bc.value.trim(),cost:+f_c.value||0,price:+f_pr.value||0,discount:+f_d.value||0,colors:f_col.value.split(',').map(x=>x.trim()).filter(Boolean),sizes:f_sz.value.split(',').map(x=>x.trim()).filter(Boolean),gtin:f_gtin.value.trim(),variants:[]};if(edit){let i=s.products.findIndex(z=>z.article===a);s.products[i]={...s.products[i],...x}}else s.products.push(x);toast('Карточка сохранена');show('products')}
function production(){let rows=s.batches.map(b=>`<tr><td>${b.date}</td><td>${b.article}</td><td>${b.color||'—'}</td><td><b>${b.qty}</b></td><td>${b.breakdown||'—'}</td></tr>`).join('');let x=s.products[0]||{sizes:[],colors:[]};let sizeRows=(x.sizes||[]).map((z,i)=>`<div class="size-row"><div class="size-name">${z}</div><div class="size-dash">—</div><input class="size-qty" id="sz_${i}" data-size="${z}" type="number" min="0" value="0" oninput="calcProductionTotal()"><span>шт.</span></div>`).join('');document.getElementById('app').innerHTML=`<div class=card><h2>Производство</h2><div class=form><div class=field><label>Товар</label><select id=ba onchange=renderProductionSizes()>${s.products.map(x=>`<option value="${x.article}">${x.article} — ${x.name}</option>`).join('')}</select></div><div class=field><label>Цвет</label><select id=bcolor>${(x.colors||[]).map(c=>`<option>${c}</option>`).join('')}<option value="">Другой цвет…</option></select></div></div><div class=card size-card><div class=section-head><div><b>Количество по размерам</b><div class=muted>Каждый размер вводится отдельно. Общее количество посчитается автоматически.</div></div><div class=total-box>Итого: <b id=prodTotal>0</b> шт.</div></div><div id=sizeRows>${sizeRows||'<div class=muted>У товара пока не заданы размеры. Добавь их в карточке товара.</div>'}</div></div><div class=field style="margin-top:14px"><label>Комментарий к партии (необязательно)</label><input id=bnote placeholder="Например: партия от 09.09.2026"></div><p><button class=btn onclick=createBatch()>Добавить на склад</button></p><div class=note>После добавления партия сразу увеличивает остаток внутреннего склада. В партии сохраняется отдельная разбивка по каждому размеру.</div></div><div style="margin-top:18px"><table><tr><th>Дата</th><th>Артикул</th><th>Цвет</th><th>Количество</th><th>Разбивка по размерам</th></tr>${rows||'<tr><td colspan=5>Партий пока нет</td></tr>'}</table></div>`;calcProductionTotal()}
function renderProductionSizes(){let x=p(ba.value)||{sizes:[],colors:[]};let color=document.getElementById('bcolor');if(color)color.innerHTML=(x.colors||[]).map(c=>`<option>${c}</option>`).join('')+'<option value="">Другой цвет…</option>';let holder=document.getElementById('sizeRows');holder.innerHTML=(x.sizes||[]).map((z,i)=>`<div class="size-row"><div class="size-name">${z}</div><div class="size-dash">—</div><input class="size-qty" id="sz_${i}" data-size="${z}" type="number" min="0" value="0" oninput="calcProductionTotal()"><span>шт.</span></div>`).join('')||'<div class=muted>У товара пока не заданы размеры. Добавь их в карточке товара.</div>';calcProductionTotal()}
function calcProductionTotal(){let total=[...document.querySelectorAll('.size-qty')].reduce((a,e)=>a+(+e.value||0),0);let el=document.getElementById('prodTotal');if(el)el.textContent=total}
function createBatch(){let inputs=[...document.querySelectorAll('.size-qty')];let breakdown=inputs.filter(e=>(+e.value||0)>0).map(e=>`${e.dataset.size}:${+e.value}`).join('; ');let q=inputs.reduce((a,e)=>a+(+e.value||0),0);if(q<=0)return alert('Укажите количество хотя бы для одного размера');s.batches.push({date:new Date().toLocaleDateString('ru-RU'),article:ba.value,qty:q,color:bcolor.value,breakdown,note:bnote.value.trim()});s.movements.push({date:new Date().toLocaleString('ru-RU'),type:'production',article:ba.value,qty:q,ref:'Партия производства',color:bcolor.value,breakdown});toast('Партия добавлена на склад');show('production')}
function warehouse(){let by={};s.movements.forEach(m=>{by[m.article]=(by[m.article]||0)+(m.type==='sale'||m.type==='toWB'||m.type==='writeoff'?-m.qty:m.qty)});let rows=Object.entries(by).map(([a,q])=>`<tr><td><b>${a}</b></td><td>${p(a)?.name||''}</td><td class=${q<0?'bad':''}>${q}</td><td>${p(a)?.colors?.join(', ')||'—'}</td><td>${p(a)?.sizes?.join(', ')||'—'}</td></tr>`).join('');document.getElementById('app').innerHTML=`<div class=grid><div class=card><small>Единиц на внутреннем складе</small><div class=num>${Math.max(0,stockTotal())}</div></div><div class=card><small>Резерв FBS</small><div class=num>${s.orders.filter(o=>o.status==='На сборке').length}</div></div><div class=card><small>КИЗ в CLARA</small><div class=num>${s.kiz.length}</div></div><div class=card><small>Ошибки маркировки</small><div class=num>${s.kiz.filter(k=>k.status==='Ошибка').length}</div></div></div><div class=card style="margin-top:18px"><h2>Остатки по товарам</h2><table><tr><th>Артикул</th><th>Товар</th><th>Остаток</th><th>Цвета</th><th>Размеры</th></tr>${rows||'<tr><td colspan=5>Нет движений</td></tr>'}</table></div>`}
function wb(){document.getElementById('app').innerHTML=`<div class=card><h2>Wildberries</h2><p><span class=tag>API не подключён</span></p><div class=grid><div><b>Заказы</b><p class=muted>Будут загружаться автоматически через WB API.</p></div><div><b>Остатки WB</b><p class=muted>Синхронизация по размерам/баркодам.</p></div><div><b>Продажи и возвраты</b><p class=muted>Финансовые отчёты и детализация.</p></div><div><b>Стикеры</b><p class=muted>Генерация/получение стикера заказа.</p></div></div><p class=note>Токен WB пока не вводим в браузер. Сначала закончим серверный контур.</p></div>`}
function seedOrder(){let x=s.products[0];s.orders.unshift({id:'FBS-'+Date.now().toString().slice(-6),article:x.article,name:x.name,size:x.sizes?.[2]||'52',color:x.colors?.[0]||'чёрный',status:'Новый',barcode:x.barcode||'',sticker:'Стикер готов к печати',kiz:null});save();fbs()}
function fbs(){let orders=s.orders;let list=orders.map(o=>`<div class=order onclick="selectOrder('${o.id}')"><b>${o.id}</b> <span class=tag>${o.status}</span><div style="margin-top:7px">${o.article} · ${o.name}</div><small>${o.color||'—'} · размер ${o.size||'—'} · КИЗ: ${o.kiz||'не привязан'}</small></div>`).join('');let o=s.orders.find(x=>x.id===s.selectedOrder);document.getElementById('app').innerHTML=`<div class=hero><div><h2>FBS — рабочее место сборщика</h2><div class=muted>Скан заказа → печать стикера → скан КИЗ → проверка → готово</div></div><button class=btn light onclick=seedOrder()>+ Тестовый FBS-заказ</button></div><div class=fbsgrid><div class=card><label>Сканер штрихкода заказа</label><input id=orderScan class=scan autofocus placeholder="Наведите сканер и сканируйте заказ" onkeydown="if(event.key==='Enter')handleOrderScan(this.value)"><div style="margin-top:14px">${list||'<div class=muted>Заказов пока нет. После WB API они появятся автоматически.</div>'}</div></div><div class=card>${o?fbsDetail(o):'<div class=muted>Выберите заказ слева или отсканируйте штрихкод заказа.</div>'}</div></div>`}
function selectOrder(id){s.selectedOrder=id;fbs()}
function handleOrderScan(v){let code=v.trim();let o=s.orders.find(x=>x.id===code||x.barcode===code);if(!o){o={id:code||'FBS-'+Date.now(),article:s.products[0].article,name:s.products[0].name,size:s.products[0].sizes?.[0]||'48',color:s.products[0].colors?.[0]||'—',status:'Новый',barcode:code,sticker:'Стикер готов к печати',kiz:null};s.orders.unshift(o)}s.selectedOrder=o.id;o.status='Стикер сформирован';save();fbs();setTimeout(()=>window.print(),150);}
function fbsDetail(o){return `<h2>${o.id}</h2><div class=steps><div class="step on">1. Заказ</div><div class="step ${o.status!=='Новый'?'on':''}">2. Стикер</div><div class="step ${o.kiz?'on':''}">3. КИЗ</div><div class="step ${o.status==='Готов к отгрузке'?'on':''}">4. FBS</div></div><table><tr><td>Артикул</td><td><b>${o.article}</b></td></tr><tr><td>Размер / цвет</td><td>${o.size} / ${o.color}</td></tr><tr><td>Баркод</td><td>${o.barcode||'—'}</td></tr><tr><td>КИЗ</td><td>${o.kiz||'не привязан'}</td></tr></table><div style="margin-top:14px"><button class=btn onclick="printSticker('${o.id}')">🖨 Печать стикера</button> <button class="btn green" onclick="focusKiz()">Сканировать КИЗ</button></div><input id=kizScan style="margin-top:12px" class=scan placeholder="Сканируйте КИЗ" onkeydown="if(event.key==='Enter')handleKizScan(this.value,'${o.id}')"><p class=note>После скана CLARA проверит код, привяжет его к FBS-заказу и переведёт заказ в «Готов к отгрузке». Реальный вывод из оборота ЧЗ выполняется после подключения серверного API.</p>`}
function printSticker(id){let o=s.orders.find(x=>x.id===id);document.getElementById('app').innerHTML=`<div class=print-area><div class=printbox><b>СТИКЕР ЗАКАЗА</b><div class=sticker><b>CLARA / WILDBERRIES</b><hr>Заказ: ${o.id}<br>Артикул: ${o.article}<br>Размер: ${o.size}<br>Цвет: ${o.color}<br>Баркод: ${o.barcode||'—'}<br><br><b>ПОДГОТОВЛЕНО К ОТГРУЗКЕ</b></div><button class="btn hide-print" onclick="window.print()">Печать</button> <button class="btn light hide-print" onclick="fbs()">Назад</button></div></div>`;setTimeout(()=>window.print(),100)}
function focusKiz(){document.getElementById('kizScan')?.focus()} function handleKizScan(v,id){let code=v.trim();if(!code)return;let o=s.orders.find(x=>x.id===id);let existing=s.kiz.find(k=>k.code===code);if(existing&&existing.orderId!==id){o.status='Ошибка';toast('Этот КИЗ уже привязан к другому заказу');return}let k=existing||{code,status:'Зарезервирован FBS',orderId:id,article:o.article,date:new Date().toLocaleString('ru-RU')};if(!existing)s.kiz.push(k);k.status='Зарезервирован FBS';k.orderId=id;o.kiz=code;o.status='Готов к отгрузке';s.movements.push({date:new Date().toLocaleString('ru-RU'),type:'reserveFBS',article:o.article,qty:1,ref:id,kiz:code});save();toast('КИЗ привязан к FBS-заказу');fbs()}
function mark(){let rows=s.kiz.map(k=>`<tr><td>${k.code}</td><td>${k.article}</td><td>${k.orderId||'—'}</td><td>${k.status}</td><td>${k.date||''}</td></tr>`).join('');document.getElementById('app').innerHTML=`<div class=hero><div><h2>Честный ЗНАК</h2><div class=muted>Единый журнал кодов и операций</div></div><button class=btn onclick=addKiz()>+ Добавить КИЗ</button></div><div class=grid><div class=card><small>Всего кодов</small><div class=num>${s.kiz.length}</div></div><div class=card><small>В обороте</small><div class=num>${s.kiz.filter(k=>k.status==='В обороте').length}</div></div><div class=card><small>Зарезервировано FBS</small><div class=num>${s.kiz.filter(k=>k.status==='Зарезервирован FBS').length}</div></div><div class=card><small>Выведено</small><div class=num>${s.kiz.filter(k=>k.status==='Выведен').length}</div></div></div><div class=card style="margin-top:18px"><h3>Журнал КИЗ</h3><table><tr><th>КИЗ</th><th>Артикул</th><th>FBS</th><th>Статус</th><th>Дата</th></tr>${rows||'<tr><td colspan=5>Кодов пока нет</td></tr>'}</table></div><div class=card style="margin-top:18px"><b>Операции API</b><p class=note>Ввод в оборот → резерв → отгрузка → вывод из оборота → возврат. Здесь будет серверная интеграция с Честным ЗНАКом; браузерный интерфейс уже подготовлен.</p></div>`}
function addKiz(){let code=prompt('Отсканируйте/вставьте КИЗ');if(!code)return;s.kiz.push({code:code.trim(),status:'В обороте',orderId:null,article:'',date:new Date().toLocaleString('ru-RU')});save();mark()}
function calcUnit(x,spp){
 let base=(x.price||0)*(1-(x.discount||0)/100); let buyer=base*(1-spp);
 let commission=buyer*s.settings.commission, acq=buyer*s.settings.acq, ads=buyer*s.settings.ads, tax=buyer*s.settings.tax;
 let logistics=(buyer*s.settings.logistics)/Math.max(.01,s.settings.buyout);
 let profit=buyer-commission-acq-ads-tax-logistics-x.cost;
 return {buyer,commission,acq,ads,tax,logistics,profit,margin:buyer?profit/buyer:0};
}
function unit(){
 let x=s.products.find(z=>z.article===(window.unitArticle||s.products[0]?.article))||s.products[0];
 let spp=Number.isFinite(window.unitSpp)?window.unitSpp:s.settings.spp;
 let r=x?calcUnit(x,spp):{buyer:0,commission:0,acq:0,ads:0,tax:0,logistics:0,profit:0,margin:0};
 let scenarios=[10,15,20,22,25,25.8,27,30,35,40].map(v=>{let q=calcUnit(x,v/100);return `<tr><td>${v}%</td><td>${money(q.buyer)}</td><td>${money(q.commission)}</td><td>${money(q.logistics)}</td><td>${money(q.ads)}</td><td class=${q.profit<0?'bad':q.profit<100?'yellow':'ok'}>${money(q.profit)}</td><td>${pc(q.margin)}</td></tr>`}).join('');
 document.getElementById('app').innerHTML=`<div class=hero><div><h2>Юнит-экономика</h2><div class=muted>Ручное изменение СПП и мгновенный пересчёт результата</div></div></div>
 <div class=card><div class=form><div class=field><label>Товар</label><select id=unitProduct onchange="unitArticle=this.value;unit()">${s.products.map(z=>`<option value="${z.article}" ${z.article===x?.article?'selected':''}>${z.article} — ${z.name}</option>`).join('')}</select></div><div class=field><label>Размер (для сценария)</label><select id=unitSize><option>Все размеры</option>${(x?.sizes||[]).map(z=>`<option>${z}</option>`).join('')}</select></div><div class=field><label>СПП, % — вручную</label><input id=unitSpp type=number step=.1 value=${(spp*100).toFixed(1)} oninput="unitSpp=Number(this.value)/100;unit()"></div></div></div>
 <div class=grid style="margin-top:14px"><div class=card><small>Цена покупателя</small><div class=num>${money(r.buyer)}</div></div><div class=card><small>Чистая прибыль</small><div class="num ${r.profit<0?'bad':r.profit<100?'yellow':'ok'}">${money(r.profit)}</div></div><div class=card><small>Маржа</small><div class=num>${pc(r.margin)}</div></div><div class=card><small>Себестоимость</small><div class=num>${money(x?.cost)}</div></div></div>
 <div class=card style="margin-top:18px"><h3>Сценарии СПП</h3><p class=note>Меняй СПП и сразу смотри, сколько останется после комиссии, логистики, рекламы, эквайринга, налога и себестоимости.</p><table><tr><th>СПП</th><th>Цена покупателя</th><th>КВВ</th><th>Логистика</th><th>ДРР</th><th>Чистая прибыль</th><th>Маржа</th></tr>${scenarios}</table></div>`;
}
function analytics(){
 let sold=s.movements.filter(m=>m.type==='sale').reduce((a,m)=>a+m.qty,0), orders=s.orders.length, kiz=s.kiz.length, batches=s.batches.length;
 document.getElementById('app').innerHTML=`<div class=card><div class=hero><div><h2>Аналитика продаж</h2><div class=muted>Единый аналитический контур CLARA: WB сейчас, Ozon готов к подключению API</div></div><div class=seg><button class=btn onclick="toast('WB выбран')">WB</button><button class="btn light" onclick="toast('Ozon подключим через API')">Ozon</button></div></div>
 <div class=grid><div class=card><small>Аналитика</small><div class=num>${sold}</div><p class=muted>Продано, шт.</p></div><div class=card><small>Лента заказов</small><div class=num>${orders}</div><p class=muted>Заказов FBS</p></div><div class=card><small>Журнал товара</small><div class=num>${s.products.length}</div><p class=muted>Артикулов</p></div><div class=card><small>КИЗ</small><div class=num>${kiz}</div><p class=muted>Кодов в CLARA</p></div></div></div>
 <div class=card style="margin-top:18px"><h3>Разделы аналитики</h3><div class=analytics-menu>${['Аналитика','Лента заказов','Карта заказов','Реклама','Реклама · Дни (бета)','Конкуренты','Поисковые запросы','Unit-экономика','Коэффициенты логистики','Журнал товара','Товары','Себестоимость'].map((v,i)=>`<button class="menu-tile" onclick="toast('${v}: подготовлено под подключение данных')"><b>${v}</b><span>${i===3||i===4?'Реклама':'Открыть раздел'}</span></button>`).join('')}</div></div>
 <div class=card style="margin-top:18px"><h3>Что подключим через API</h3><p class=note>Продажи, заказы, возвраты, рекламные расходы, поисковые запросы, логистика, остатки, коэффициенты и финансовые показатели будут заполняться автоматически после серверной интеграции.</p></div>`;
}
function reports(){document.getElementById('app').innerHTML=`<div class=grid><div class=card><small>Заказов FBS</small><div class=num>${s.orders.length}</div></div><div class=card><small>КИЗ операций</small><div class=num>${s.kiz.length}</div></div><div class=card><small>Производственных партий</small><div class=num>${s.batches.length}</div></div><div class=card><small>Движений склада</small><div class=num>${s.movements.length}</div></div></div><div class=card style="margin-top:18px"><h2>Контроль CLARA</h2><p>Позже сюда подключаем WB отчёты, рекламу, возвраты, налог, чистую прибыль и рекомендации «что шить».</p></div>`}
function settings(){let x=s.settings;document.getElementById('app').innerHTML=`<div class=card><h2>Настройки</h2><div class=form>${[['СПП','spp'],['Комиссия WB','commission'],['Эквайринг','acq'],['ДРР','ads'],['Налог','tax'],['Выкуп','buyout'],['Логистика','logistics']].map(([n,k])=>`<div class=field><label>${n} %</label><input id=i_${k} type=number step=.1 value=${x[k]*100}></div>`).join('')}<div class=field><label>Возвратная логистика ₽</label><input id=i_return type=number value=${x.returnLogistics}></div></div><p><button class=btn onclick=saveSettings()>Сохранить</button></p></div>`}
function saveSettings(){['spp','commission','acq','ads','tax','buyout','logistics'].forEach(k=>s.settings[k]=+document.getElementById('i_'+k).value/100);s.settings.returnLogistics=+i_return.value||0;save();toast('Настройки сохранены');show('settings')}
show('home');
